### ISSUE TITLE
windows sandbox

### ISSUE THREAD

**Issue by ghost** [NotRequiem/VMAware#1]
does not detect windows sandbox. might be something you want to look into! cool project otherwise though!

**Comment by kernelwernel** [comment]
> does not detect windows sandbox. might be something you want to look into! cool project otherwise though!

Ouch, I haven't extensively tested it on Windows due to my low RAM being a massive barrier with running VMs. 

Is it possible if you could give me information like which VM you used?

Also, you don't have to do this but I've added a debug log feature for development purposes. If you could `git pull` then build the project with `cmake -DCMAKE_BUILD_TYPE=Debug ..` instead of `cmake ..` then it can be recompiled with additional logs for any debugging. If you could show the result then that would be incredibly helpful.

thanks for the kind words though :)

**Comment by 90th** [comment]
@kernelwernel 
> > does not detect windows sandbox. might be something you want to look into! cool project otherwise though!
> 
> Ouch, I haven't extensively tested it on Windows due to my low RAM being a massive barrier with running VMs.
> 
> Is it possible if you could give me information like which VM you used?
> 
> Also, you don't have to do this but I've added a debug log feature for development purposes. If you could `git pull` then build the project with `cmake -DCMAKE_BUILD_TYPE=Debug ..` instead of `cmake ..` then it can be recompiled with additional logs for any debugging. If you could show the result then that would be incredibly helpful.
> 
> thanks for the kind words though :)

Pretty sure windows sandbox uses a microsoft hyper-v hypervisor

**Comment by kernelwernel** [comment]
> @kernelwernel
> 
> > > does not detect windows sandbox. might be something you want to look into! cool project otherwise though!
> > 
> > 
> > Ouch, I haven't extensively tested it on Windows due to my low RAM being a massive barrier with running VMs.
> > Is it possible if you could give me information like which VM you used?
> > Also, you don't have to do this but I've added a debug log feature for development purposes. If you could `git pull` then build the project with `cmake -DCMAKE_BUILD_TYPE=Debug ..` instead of `cmake ..` then it can be recompiled with additional logs for any debugging. If you could show the result then that would be incredibly helpful.
> > thanks for the kind words though :)
> 
> Pretty sure windows sandbox uses a microsoft hyper-v hypervisor

i'll try to focus more on hyperv techniques then. I haven't focused much on that VM brand but I'll set that as my priority

**Comment by unusual-aspect** [comment]
![sandbox](https://github.com/kernelwernel/VMAware/assets/10220406/bd71d32c-a352-42a2-a584-8f89bf1a02d0)
Maybe this will help ;)

**Comment by kernelwernel** [comment]
> ![sandbox](https://private-user-images.githubusercontent.com/10220406/311727071-bd71d32c-a352-42a2-a584-8f89bf1a02d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2NDY3NDEsIm5iZiI6MTcxMDY0NjQ0MSwicGF0aCI6Ii8xMDIyMDQwNi8zMTE3MjcwNzEtYmQ3MWQzMmMtYTM1Mi00MmEyLWE1ODQtOGY4OWJmMWEwMmQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDAzMzQwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0OGU3ZDBiMDVmNjQxNDRhMmEzMGYzZTEwZGIyNTY3YTJlOTA0MGNjMzZhMDRhOWRhOWRjMjJhNGJkNTMwZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YxC6awZ1N4YUDRZoLJG3tDCWu91s36y7CAusUp6bevQ) Maybe this will help ;)

Thanks! I actually added a new technique [here](https://github.com/kernelwernel/VMAware/commit/c4b6220e0ca87103fc4f6716b44e1ac64e972346) based on the screenshot, appreciate it :)
