### ISSUE TITLE
wcstombs: This function or variable may be unsafe

### ISSUE THREAD

**Issue by GhostDog98** [NotRequiem/VMAware#102]
When attempting to compile using VS, I receive the following error:
```
'wcstombs': This function or variable may be unsafe. Consider using wcsombs_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
```
While using this option does disable it, it'd be great to have this fixed.

**Comment by kernelwernel** [comment]
fixed [here](https://github.com/kernelwernel/VMAware/pull/103/commits/c9011d6c214c4ff2622f27fef1fed55175a2278d), i'll soon update it to the 1.6 version which will include the fix.

Thanks for reporting this issue btw!
