### ISSUE TITLE
Wrong flag given.

### ISSUE THREAD

**Issue by PrimeMonket** [NotRequiem/VMAware#114]
After running VMAware in terminal i got this output along with a positive result due to what is ebing said below as a result of this i decided to copy paste the flag `--discard-hyperv-host` but upon running i was given `Unknown argument provided, consult the help menu with --help` which is what i had copy and pasted from below upon checking the help menu with --help i relasied you had run with the flag `--disable-hyperv-host` so all in all small typo to be chnaged in commits thanks for the work outside of this works a charm.

```
[    NOTE    ] If you know you are running on host, Hyper-V virtualises all applications by default within the host system. This result is in fact correct and NOT a false positive. If you do not want Hyper-V's default virtualisation enabled, run with the "--discard-hyperv-host" argument. See here https://github.com/kernelwernel/VMAware/issues/75
====== CONCLUSION: Running inside a Microsoft Hyper-V VM ======
```

**Comment by kernelwernel** [comment]
fixed https://github.com/kernelwernel/VMAware/pull/115
