### ISSUE TITLE
Add sneaky detections

### ISSUE THREAD

**Issue by namtacs** [NotRequiem/VMAware#129]
1. How many USBs does this computer know. Go example - https://github.com/EvilBytecode/GoDefender/blob/main/AntiVirtualization/USBCheck/USBCheck.go
2. \> 20 files in file activity. Go example -  https://github.com/EvilBytecode/GoDefender/blob/main/AntiVirtualization/RecentFileActivity/RecentFileActivity.go

**Comment by kernelwernel** [comment]
thanks for the suggestions!

1. i don't think this is a useful detection if i'm being honest. I can definitely see something like that receiving a false positive for sure.

2. kinda the same, that's something that someone can definitely spoof very easily. I already have a lot of spoofable techniques that are implemented, but not those where only a few clicks with minimal effort would be enough to bypass it. 

I appreciate for the suggestions but I can't really find any practical use for them for a library that has 0 tolerance for false positives and tries its best to not use extremely easy-to-bypass techniques. Thank you though. I'll definitely check out all the other VM detections in that repository for sure.
