### ISSUE TITLE
Windows 11 false detection VM certainty: 100%

### ISSUE THREAD

**Issue by UnrealKaraulov** [NotRequiem/VMAware#137]
Running in baremetal
VM certainty: 100%

Tested with latest commit.

Default console app test. Why Windows 11 detected as "baremetal" virtual pc ?

**Comment by kernelwernel** [comment]
Can I ask why this was closed? @UnrealKaraulov

**Comment by UnrealKaraulov** [comment]
@kernelwernel i think this is valid result ?
