### ISSUE TITLE
any.run virtual pc not detected

### ISSUE THREAD

**Issue by UnrealKaraulov** [NotRequiem/VMAware#138]
any.run virtual pc not detected as Virtual Machine.

**Comment by kernelwernel** [comment]
is it possible if you can run it again but with the debug binary and send the full output? It would be super useful to know where the problem is. I think I have an idea but I just want to be 100% sure:

https://github.com/kernelwernel/VMAware/actions/runs/10621487315/artifacts/1871647628

**Comment by UnrealKaraulov** [comment]
@kernelwernel 

![image](https://github.com/user-attachments/assets/779885fb-ce83-4ea6-9ce1-5c5dfddc0b4b)

**Comment by kernelwernel** [comment]
> @kernelwernel
> 
> ![image](https://private-user-images.githubusercontent.com/88730285/363460342-779885fb-ce83-4ea6-9ce1-5c5dfddc0b4b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxNjc3NzAsIm5iZiI6MTcyNTE2NzQ3MCwicGF0aCI6Ii84ODczMDI4NS8zNjM0NjAzNDItNzc5ODg1ZmItY2U4My00ZWE2LTljZTEtNWM1ZGZkZGMwYjRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAxVDA1MTExMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlODFlMGQxMTFhZGE4OWI2ZGJjYjg2Mjg5MzlhYTE5NjQzZGVkODc1MDY4MjZmYmQyZDUyYmJhZDA3ZWRlMmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WyX5yjXiCqYRpOpqviNgPK_eIBQPap__UmXeS0Hvo9g)

you can download it here: https://answers.microsoft.com/en-us/windows/forum/all/msvcp140ddll-is-missing-from-your-computer/c253126e-8f11-45d0-828d-8ede40c3126a

**Comment by UnrealKaraulov** [comment]
I run release binaries

![image](https://github.com/user-attachments/assets/b250f7f3-4c24-4d3d-8a07-dd8755f7dbaf)
![image](https://github.com/user-attachments/assets/bf34c684-41f6-4cda-b674-78d219dc680c)

**Comment by kernelwernel** [comment]
uhhhhh, not sure why you got that result honestly. I really need to get debugs from the debug binary i linked you earlier, because I can't really gain any information from the release binary.

**Comment by UnrealKaraulov** [comment]
I can't download visual studio redistributable (just can't enter it in browser tab, because any.run pressed ctrl button when do input, any run issue)

**Comment by UnrealKaraulov** [comment]
@kernelwernel If I tried to download but when install redistributable I got error:
![image](https://github.com/user-attachments/assets/ef71367f-4e3b-4a32-a6f1-114eb1c10a52)


sorry but I can't run debug binaries...

**Comment by kernelwernel** [comment]
but... are you 100% sure any.run is running in a VirtualPC VM? Because if it is then it seems to have a lot of anti-anti-VM features from the looks of the result. I'm really not sure why bochs was detected as positive frankly. I'll try to have debug outputs in a release binary then, if it's ok to you?

**Comment by UnrealKaraulov** [comment]
@kernelwernel I don't know VirtualPC or not, but this works: https://github.com/kkent030315/detect-anyrun

**Comment by kernelwernel** [comment]
> @kernelwernel I don't know VirtualPC or not, but this works: https://github.com/kkent030315/detect-anyrun

the library has no support for any.run yet, but this is an extremely useful repository. I'll definitely add support for any.run in the next release. Thanks. 

I've also finished generating the release binary with debug logs, this should work now:
https://github.com/kernelwernel/VMAware/actions/runs/10651338144/artifacts/1878869863

**Comment by UnrealKaraulov** [comment]
@kernelwernel 
[log.txt](https://github.com/user-attachments/files/16827476/log.txt)

This log?

**Comment by UnrealKaraulov** [comment]
@kernelwernel 

Not related to this issue, but if I disable or enable additional cpu threads in my BIOS, it can be detected as VM ?

I run this release debug binaries on my PC (windows 11) and got result: 
![image](https://github.com/user-attachments/assets/77cd7b6c-3b5e-4424-9e73-8ec45290e388)

**Comment by kernelwernel** [comment]
> @kernelwernel
> 
> Not related to this issue, but if I disable or enable additional cpu threads in my BIOS, it can be detected as VM ?
> 
> I run this release debug binaries on my PC (windows 11) and got result: ![image](https://private-user-images.githubusercontent.com/88730285/363461310-77cd7b6c-3b5e-4424-9e73-8ec45290e388.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxNjkzODUsIm5iZiI6MTcyNTE2OTA4NSwicGF0aCI6Ii84ODczMDI4NS8zNjM0NjEzMTAtNzdjZDdiNmMtM2I1ZS00NDI0LTllNzMtOGVjNDUyOTBlMzg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAxVDA1MzgwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4NjJhZGM5NGIwMzUzNWYyYmIwNzViNzM5YzI3NGVhM2Y3MjU4YzRmY2MxYzRiZjA1MzdiMTUwMzU1ZDZlNDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hvS5as-kgm6ReiG1T4zzT5lV1WDjK0yIjpIKM7r1S3c)

I found where the issue is now. I messed up something with the bochs technique. I'll fix that really quick.

**Comment by UnrealKaraulov** [comment]
@kernelwernel thanks! 

But what about my question, I can enable or disable additional thread technique in BIOS for my Ryzen CPU and it not affect to vmaware results ?  (change from 8 to 16 threads) 

I found, name 'SMT' in bios settings.

**Comment by kernelwernel** [comment]
> @kernelwernel thanks!
> 
> But what about my question, I can enable or disable additional thread technique in BIOS for my Ryzen and it not affect to vmaware results ? (change from 8 to 16 threads)
> 
> I found, name 'SMT' in bios settings.

i don't think it will affect the result frankly. If you had an Intel CPU then it would, because the `VM::INTEL_THREAD_MISMATCH` will compare your CPU for every Intel CPU brand's thread count and match if it's different from that of the database of threadcounts.

So for AMD? no. Intel? Yes.

**Comment by kernelwernel** [comment]
Also, thank you for the help. This has been very helpful, I'll start working on adding any.run detections. :+1: 

If you have any more issues, let me know! I'd be glad to discuss.

**Comment by UnrealKaraulov** [comment]
@kernelwernel virustotal virtual machines not detected too?

![image](https://github.com/user-attachments/assets/85d97811-9d77-4add-9290-29e0af963d01)

**Comment by kernelwernel** [comment]
> @kernelwernel virustotal virtual machines not detected too?

VirusTotal doesn't necessarily have a clear base VM brand, which is why I didn't add it because there's little to no information about what VM it uses, not to mention there might be different VM brands for each antivirus that VirusTotal supports.  

**EDIT:** nvm, I was making this before you deleted

**Comment by UnrealKaraulov** [comment]
@kernelwernel I tested and it detect many VM from virustotal, thanks for vmaware project!

**Comment by kernelwernel** [comment]
> @kernelwernel I tested and it detect many VM from virustotal, thanks for vmaware project!

Thanks! glad to hear it worked :) 

And thanks for being helpful!

**Comment by kernelwernel** [comment]
added here: https://github.com/kernelwernel/VMAware/releases/tag/v1.9

thanks for the suggestion!
