### ISSUE TITLE
Temperature checks?

### ISSUE THREAD

**Issue by redactedontop** [NotRequiem/VMAware#141]
May I ask, does this have Windows temperature checks? If not, could you provide me with a way to contact you (I can supply you some methods ;3)?

**Comment by kernelwernel** [comment]
> May I ask, does this have Windows temperature checks? If not, could you provide me with a way to contact you (I can supply you some methods ;3)?

Hmm nope, there's only Linux temperature checks at the moment. You can contact me on discord at `kr.nl` or by email if that's ok, preferably discord :)
