### ISSUE TITLE
My vm test 2/122 . networkexplorer.dll think false

### ISSUE THREAD

**Issue by RageCarry** [NotRequiem/VMAware#168]
Seems false, I run it in cmd as admin "vmaware --all", same for host
DLL: LIB_INST detected true for real dll = networkexplorer.dll

And anticheats... Pepesad
![Untitled](https://github.com/user-attachments/assets/fcd1356b-c977-4cd6-98ad-edf5d849bb87)

**Comment by RageCarry** [comment]
https://github.com/kernelwernel/VMAware/blob/c5fc58cb08a39efec282c759573c9016601b0dc7/src/vmaware.hpp#L5084

Thats not enought, read range from 0x40000000 to 0x400000FF

**Comment by kernelwernel** [comment]
> Seems false, I run it in cmd as admin "vmaware --all", same for host DLL: LIB_INST detected true for real dll = networkexplorer.dll
> 
> And anticheats... Pepesad ![Untitled](https://private-user-images.githubusercontent.com/83500464/382864278-fcd1356b-c977-4cd6-98ad-edf5d849bb87.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3NDY2OTIsIm5iZiI6MTczMDc0NjM5MiwicGF0aCI6Ii84MzUwMDQ2NC8zODI4NjQyNzgtZmNkMTM1NmItYzk3Ny00Y2Q2LTk4YWQtZWRmNWQ4NDliYjg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA0VDE4NTMxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3YTU2ZWM2MzI1NWYxZjcwODk2Zjk0ZGYxMDM0NDZlNTY2MGE5ZDNjZjhjNDE3ODdlMDc0OTk3NWJmNjhjMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.nE_kCYfY-L7-8t6gI3kj8mOpELd0QuVRowWfbogxlo8)

I see, what did you receive for the result without "--all" though? Because the lib doesn't run all the techniques by default due to things like this happening with spoofable or error-prone techniques, which is what happened here. I'll temporarily remove this technique from the lib and discuss it with my co-maintainer. 

Also, what was the other technique that was detected apart from the DLL check?

**Comment by RageCarry** [comment]
> > Seems false, I run it in cmd as admin "vmaware --all", same for host DLL: LIB_INST detected true for real dll = networkexplorer.dll
> > And anticheats... Pepesad ![Untitled](https://private-user-images.githubusercontent.com/83500464/382864278-fcd1356b-c977-4cd6-98ad-edf5d849bb87.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3NDY2OTIsIm5iZiI6MTczMDc0NjM5MiwicGF0aCI6Ii84MzUwMDQ2NC8zODI4NjQyNzgtZmNkMTM1NmItYzk3Ny00Y2Q2LTk4YWQtZWRmNWQ4NDliYjg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA0VDE4NTMxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3YTU2ZWM2MzI1NWYxZjcwODk2Zjk0ZGYxMDM0NDZlNTY2MGE5ZDNjZjhjNDE3ODdlMDc0OTk3NWJmNjhjMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.nE_kCYfY-L7-8t6gI3kj8mOpELd0QuVRowWfbogxlo8)
> 
> I see, what did you receive for the result without "--all" though? Because the lib doesn't run all the techniques by default due to things like this happening with spoofable or error-prone techniques, which is what happened here. I'll temporarily remove this technique from the lib and discuss it with my co-maintainer.
> 
> Also, what was the other technique that was detected apart from the DLL check?

Without all 0 detections, other detection is RDTSC locky trick

**Comment by kernelwernel** [comment]
> > > Seems false, I run it in cmd as admin "vmaware --all", same for host DLL: LIB_INST detected true for real dll = networkexplorer.dll
> > > And anticheats... Pepesad ![Untitled](https://private-user-images.githubusercontent.com/83500464/382864278-fcd1356b-c977-4cd6-98ad-edf5d849bb87.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3NDY2OTIsIm5iZiI6MTczMDc0NjM5MiwicGF0aCI6Ii84MzUwMDQ2NC8zODI4NjQyNzgtZmNkMTM1NmItYzk3Ny00Y2Q2LTk4YWQtZWRmNWQ4NDliYjg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA0VDE4NTMxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3YTU2ZWM2MzI1NWYxZjcwODk2Zjk0ZGYxMDM0NDZlNTY2MGE5ZDNjZjhjNDE3ODdlMDc0OTk3NWJmNjhjMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.nE_kCYfY-L7-8t6gI3kj8mOpELd0QuVRowWfbogxlo8)
> > 
> > 
> > I see, what did you receive for the result without "--all" though? Because the lib doesn't run all the techniques by default due to things like this happening with spoofable or error-prone techniques, which is what happened here. I'll temporarily remove this technique from the lib and discuss it with my co-maintainer.
> > Also, what was the other technique that was detected apart from the DLL check?
> 
> Without all 0 detections, other detection is RDTSC locky trick

I disabled the faulty part of the `VM::DLL_CHECK` technique, so it should be good now. About the RDTSC technique, there's nothing much I can do because it's very common for it to give a false positive on host. It's disabled by default for that reason. 

Thanks for reporting on the issue :)

> https://github.com/kernelwernel/VMAware/blob/c5fc58cb08a39efec282c759573c9016601b0dc7/src/vmaware.hpp#L5084
> 
> Thats not enought, read range from 0x40000000 to 0x400000FF

I'll update this as well, thanks.
