### ISSUE TITLE
Compile error in xcode 

### ISSUE THREAD

**Issue by sridhard** [NotRequiem/VMAware#187]
I am trying to build the latest code from github in mac xcode. getting below errors

vmaware.hpp:725:13 No matching function for call to 'sysctlbyname'

vmaware.hpp:5957:24 Invalid operands to binary expression ('std::chrono::milliseconds' (aka 'duration<long long, ratio<1LL, 1000LL>>') and 'const u32' (aka 'const unsigned int'))

vmaware.hpp:6076:18 No member named 'has_hyperthreading' in 'VM::cpu'

**Comment by kernelwernel** [comment]
I'll find a fix for it really soon, are you using the cloned main branch or the 1.9 release?

**Comment by kernelwernel** [comment]
@sridhard I've made a few changes to the code and (I think) I fixed the issues you were facing.

Can you test the new vmaware.hpp file in the dev branch and see if the problem persists?

https://github.com/kernelwernel/VMAware/blob/dev/src/vmaware.hpp

**Comment by sridhard** [comment]
Hi,

I dev branch getting error
vmaware.hpp:734:22 Use of undeclared identifier 'HW_PHYSICALCPU'

HW_PHYSICALCPU should be HW_NCPU correct?

**Comment by kernelwernel** [comment]
> Hi,
> 
> I dev branch getting error vmaware.hpp:734:22 Use of undeclared identifier 'HW_PHYSICALCPU'
> 
> HW_PHYSICALCPU should be HW_NCPU correct?

updated, can you try it again in the dev branch?

**Comment by sridhard** [comment]
Yes. fixed

@kernelwernel I am closing the iussue. Thanks a lot for your great support

**Comment by kernelwernel** [comment]
> Yes. fixed
> 
> @kernelwernel I am closing the iussue. Thanks a lot for your great support

no problem , thanks for reporting the issue too :)
