### ISSUE TITLE
Not an issue, just needing assistance.

### ISSUE THREAD

**Issue by eyjafjallajo** [NotRequiem/VMAware#2]
Trying to compile vmaware.hpp with MSVC 2019 16.7 on c++11 standard causes total of 30 issues. 
7 out of 30 issues for example: inline variable asks for c++17. 
How to compile vmaware.hpp on c++11?

**Comment by kernelwernel** [comment]
I'll try to fix that asap. I didn't think anybody would use C++11, but I knew about the warnings prior to claiming it's C++11 compatible. I figured if it's still compilable even with the warnings, I didn't think it was a major problem. 

Thanks for pointing that out though, I'll work on it right now.

**Comment by eyjafjallajo** [comment]
Thank you!

**Comment by kernelwernel** [comment]
Not sure if you still care but I finally fixed the issues (at least according the CI tests [here](https://github.com/kernelwernel/VMAware/actions/runs/6600432983/job/17930430927)). If you still have any issues then please don't hesitate to point them out!

**Comment by eyjafjallajo** [comment]
Thank you again!
I mentioned one thing. At least for me __popcount (2323) instruction in msvc compiler called __popcnt().

**Comment by kernelwernel** [comment]
> Thank you again! I mentioned one thing. At least for me __popcount (2323) instruction in msvc compiler called __popcnt().

Strange, I'll remove the builtin popcount shortcut with a manual algorithm for MSVC if that's the case. 

[commit link](https://github.com/kernelwernel/VMAware/commit/6d25386657546c68a3ae9e0bf809991272dd7ad0)
