### ISSUE TITLE
There are many errors in using the VS2022 LLVM compiler

### ISSUE THREAD

**Issue by icyfox168168** [NotRequiem/VMAware#31]

**Comment by kernelwernel** [comment]
can you share me what the errors are? thanks for pointing this out btw. Also i didn't know that compiler even existed if i'm honest, can you give me more information about it?

**Comment by icyfox168168** [comment]
13:19:49:918	1>D:\Users\x\Documents\GitHub\VMAware\src\vmaware.hpp(773,56): error : use of undeclared identifier 'command'

**Comment by kernelwernel** [comment]
> 13:19:49:918 1>D:\Users\x\Documents\GitHub\VMAware\src\vmaware.hpp(773,56): error : use of undeclared identifier 'command'

sorry for the late reply, should be fixed with [this](https://github.com/kernelwernel/VMAware/commit/d11f5c84f4e68969d2c5258af6d94779caaa1944) commit.

can you let me know if the error still persists or if other errors appear?

**Comment by icyfox168168** [comment]
Very perfect, it can be compiled now

**Comment by kernelwernel** [comment]
> Very perfect, it can be compiled now

sounds good, thanks for reporting the issue :)
