### ISSUE TITLE
Windows/MSVC can't compile release 1.0

### ISSUE THREAD

**Issue by greenozon** [NotRequiem/VMAware#33]
Looks like there is some leftover in the release 1.0 of the source .[hpp](https://github.com/kernelwernel/VMAware/releases/download/v1.0/vmaware.hpp)

![image](https://github.com/kernelwernel/VMAware/assets/765343/4a6f4352-5b9a-4563-879f-df01060d72e9)

**Comment by greenozon** [comment]
Created PR to address it
https://github.com/kernelwernel/VMAware/pull/32

**Comment by kernelwernel** [comment]
> Created PR to address it #32

merged and fixed :+1:
