### ISSUE TITLE
Defining debug mode leads to compiler errors

### ISSUE THREAD

**Issue by greenozon** [NotRequiem/VMAware#38]
If all of a sudden you decided to see the matrix deep sea :)
by defining
```
#define __VMAWARE_DEBUG__ 
```
you'll hit something interesting ,eg:

![image](https://github.com/kernelwernel/VMAware/assets/765343/6117e34c-c67b-4ff8-92ad-c30fcf89091b)

that's cause currently the debug() routine is living inside the VM::util  space, but used outside...
what was the original intention - to keep it inside util or inside VM scope?

**Comment by greenozon** [comment]
I"ve got another debug related idea...
for the moment it's a bit hard to read the code as it has dozens (hundreds?) of patterns like for example
```
#ifdef __VMAWARE_DEBUG__
        debug("LOADED_DLLS:", "caught error, returned false");
#endif
```

the idea is to simplify/refactor approach above into something like

```
        debug("LOADED_DLLS:", "caught error, returned false");
```
meaning hide the #ifdef/endif wrapper over  the debug() construction somehow

from my past experience I"ve implemented it like
```
#ifdef __VMAWARE_DEBUG__
#define debug() ...    // here we call the original routine passing all the params, etc
#else
#define debug()      // empty -> no code generated at all if no DEBUG mode
#endif
```

Let me know if you like this idea so I could take of it
but first lets solve the original issue in the previous message
Thank you

**Comment by kernelwernel** [comment]
the `__VMAWARE_DEBUG__` macro is supposed to be defined based on the cmake build type. I designed it for development purposes without the intention of being used by anybody besides myself for internal debugging.

I sorta wanted the lib to not be verbose or output anything extra, that macro was meant to be undocumented, so yeah.

About the #ifdef/#endif preprocessors, you're right that it looks messy and there should be a far better solution to what I implemented. I'll try to work on it today if I have the time :)

**Comment by greenozon** [comment]
a try:  https://github.com/kernelwernel/VMAware/pull/39

**Comment by greenozon** [comment]
BTW, well this is actually another topic, but I"m just curious - are these escape symbols working only under Linux console?

I"m asking cause on Windows I'm observing pretty much funny pic, eg:

![image](https://github.com/kernelwernel/VMAware/assets/765343/5dab2f48-f9af-4a9c-a534-aa88eac6553c)

**Comment by greenozon** [comment]
Maybe (another improvement) it worth to put those escapes into Linux (Mac?) only #ifdef, what do you think

**Comment by kernelwernel** [comment]
> BTW, well this is actually another topic, but I"m just curious - are these escape symbols working only under Linux console?
> 
> I"m asking cause on Windows I'm observing pretty much funny pic, eg:
> 
> ![image](https://private-user-images.githubusercontent.com/765343/304886222-5dab2f48-f9af-4a9c-a534-aa88eac6553c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5NDkxMDUsIm5iZiI6MTcwNzk0ODgwNSwicGF0aCI6Ii83NjUzNDMvMzA0ODg2MjIyLTVkYWIyZjQ4LWY5YWYtNGE5Yy1hNTM0LWFhODhlYWM2NTUzYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNFQyMjEzMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYTVhODk5NjBiNGQ0ZjlmMDIwZDE1MzRmODBiZmFkODQyOWFiZDBlOWU2M2Q5YzI3YWJkMjdkZmViOWYxMzdlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XU2EoVzFd4dYAG0CyRGm0cK4EzmyuLQWHYTZgyKK9Wg)

uhhhh.... not sure about that one. I haven't made a debug build on Windows yet so that's new to me. I'll remove the escape character sequences in the next commit. And yeah I'll only add them only for Linux and MacOS for now

**Comment by kernelwernel** [comment]
merged and fixed! :+1:
