### ISSUE TITLE
MSVC: add support for Unicode build type

### ISSUE THREAD

**Issue by greenozon** [NotRequiem/VMAware#40]
When setting the Unicode chars in project settings:
![image](https://github.com/kernelwernel/VMAware/assets/765343/6def5432-7fde-4a3c-b94d-9647962e6986)

the tool has some issues, eg:

![image](https://github.com/kernelwernel/VMAware/assets/765343/5dd2fd32-9ba9-45ed-9525-58eac37418dc)

Here is a try to address above questions:   https://github.com/kernelwernel/VMAware/pull/41

**Comment by kernelwernel** [comment]
fixed and merged as always :)

Thanks for your effort!

**Comment by greenozon** [comment]
Well, no problems, that  a pleasure to contribute, but you know what?
when one enables Unicode chars, the current debug() tracer works with ANSI chars only (the lib is using cout, not wcout object
and also there are hundreds of already existing debug() statements that are using ansi strings..
so I've commented 3 debug statements and marked with //TODO Ansi or so
if you have some ideas/clues how to take care of it - lets think together!

**Comment by kernelwernel** [comment]
> Well, no problems, that a pleasure to contribute, but you know what? when one enables Unicode chars, the current debug() tracer works with ANSI chars only (the lib is using cout, not wcout object and also there are hundreds of already existing debug() statements that are using ansi strings.. so I've commented 3 debug statements and marked with //TODO Ansi or so if you have some ideas/clues how to take care of it - lets think together!

I'll leave them like that for now, i'm really busy with things irl at the moment and the project is not really my priority for now :/

I'll try to think of a solution in the future though!
