### ISSUE TITLE
Does not detect KVM Windows.

### ISSUE THREAD

**Issue by MarekKnapek** [NotRequiem/VMAware#43]
My computer is Windows Server 2022 x64 running on virtual computer in Hetzner data center using the KVM technology. Your tool provides inconsistent report.

```
[NOT DETECTED] Checking VMID...
[NOT DETECTED] Checking CPU brand...
[  DETECTED  ] Checking CPUID hypervisor bit...
[  DETECTED  ] Checking CPUID 0x4 leaf...
[  DETECTED  ] Checking hypervisor brand...
[NOT DETECTED] Checking RDTSC...
[NOT DETECTED] Checking sidt null byte...
[NOT DETECTED] Checking processor count...
[NOT DETECTED] Checking MAC address...
[NOT DETECTED] Checking temperature...
[NOT DETECTED] Checking systemd virtualisation...
[NOT DETECTED] Checking chassis vendor...
[NOT DETECTED] Checking chassis type...
[NOT DETECTED] Checking Dockerenv...
[NOT DETECTED] Checking dmidecode output...
[NOT DETECTED] Checking dmesg output...
[NOT DETECTED] Checking hwmon presence...
[  DETECTED  ] Checking cursor...
[NOT DETECTED] Checking VMware registry...
[NOT DETECTED] Checking VBox registry...
[NOT DETECTED] Checking users...
[NOT DETECTED] Checking DLLs...
[NOT DETECTED] Checking registry...
[NOT DETECTED] Checking Sunbelt...
[NOT DETECTED] Checking Wine...
[  DETECTED  ] Checking VM files...
[NOT DETECTED] Checking hw.model...
[NOT DETECTED] Checking disk size...
[NOT DETECTED] Checking VBox default specs...
[NOT DETECTED] Checking VBox network provider match...
[NOT DETECTED] Checking computer name...
[NOT DETECTED] Checking hostname...
[NOT DETECTED] Checking low memory space...
[NOT DETECTED] Checking VM processes...
[NOT DETECTED] Checking default Linux user/host...
[NOT DETECTED] Checking VBox window class...
[NOT DETECTED] Checking gamarue ransomware technique...
[NOT DETECTED] Checking WMIC outputs...
[  DETECTED  ] Checking 0x4 leaf of VMID...
[NOT DETECTED] Checking Parallels techniques...
[  DETECTED  ] Checking RDTSC VMEXIT...
[NOT DETECTED] Checking loaded DLLs...
[NOT DETECTED] Checking QEMU CPU brand...
[NOT DETECTED] Checking BOCHS CPU techniques...
[NOT DETECTED] Checking VirtualPC motherboard...
[NOT DETECTED] Checking BIOS serial number...
[NOT DETECTED] Checking Hyper-V registry...
[NOT DETECTED] Checking Hyper-V WMI output...
[NOT DETECTED] Checking VirtualBox shared folders...
[NOT DETECTED] Checking VirtualBox MSSMBIOS...
[NOT DETECTED] Checking MacOS hyperthreading...
[NOT DETECTED] Checking MacOS hw.memsize...
[NOT DETECTED] Checking MacOS registry IO-kit...
[NOT DETECTED] Checking IO registry grep...
[NOT DETECTED] Checking MacOS SIP...
[  DETECTED  ] Checking KVM registries...
[  DETECTED  ] Checking KVM drivers...
[NOT DETECTED] Checking KVM directories...

VM brand: KVM
VM certainty: 0%
VM confirmation: true

====== CONCLUSION: Running in baremetal ======
```

![cpuz1](https://github.com/kernelwernel/VMAware/assets/13893067/5d33e308-bede-4e35-959c-b4477aa3a99b)
![cpuz2](https://github.com/kernelwernel/VMAware/assets/13893067/20bb6dc9-a453-4f7f-ba42-7cd5c7e13936)
![cpuz3](https://github.com/kernelwernel/VMAware/assets/13893067/1a621306-36a2-499a-a9b8-b0e06d3b23b1)
![cpuz4](https://github.com/kernelwernel/VMAware/assets/13893067/06e2ce85-5909-4696-812b-71fd6b9be207)
![cpuz5](https://github.com/kernelwernel/VMAware/assets/13893067/506ccebc-e05b-4f34-be30-78a97e18f26e)
![cpuz6](https://github.com/kernelwernel/VMAware/assets/13893067/4a543693-d2b6-4b13-a34a-1cf23398d284)
![cpuz7](https://github.com/kernelwernel/VMAware/assets/13893067/f315b147-19a3-414e-a9e6-0b01a521d7c7)

**Comment by kernelwernel** [comment]
strange, i have a few suspicions where the problem might lie, but can you confirm that in the `
====== CONCLUSION: Running in baremetal ======` line, the text has a RED color and not a GREEN one?

**Comment by MarekKnapek** [comment]
![vsconsole](https://github.com/kernelwernel/VMAware/assets/13893067/fcfca3a6-e8bc-40c4-a633-ec4c4b57d116)

**Comment by kernelwernel** [comment]
> ![vsconsole](https://private-user-images.githubusercontent.com/13893067/307593805-fcfca3a6-e8bc-40c4-a633-ec4c4b57d116.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4NzIyODUsIm5iZiI6MTcwODg3MTk4NSwicGF0aCI6Ii8xMzg5MzA2Ny8zMDc1OTM4MDUtZmNmY2EzYTYtZThiYy00MGM0LWE2MzMtZWM0YzRiNTdkMTE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI1VDE0Mzk0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2M2Y2ZmZiMmRlZWYwMWI5YTU5YjdjMjZkNTBlNjUwM2Y0MjlkODk5OGU3ZjNlYWRlN2ZjOTA0ZmExNTZhMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._k1cB6xF8-onI8h-3unXa-7BCbaIvXf7IITJSjJb--o)

alright thanks, I'll work on this asap :)

**Comment by MarekKnapek** [comment]
There is also lot of QUEMU related hardware devices. You could also rent a virtual computer from various providers such as Hetzner, Contabo, OVH or netcup and examine each virtual machine in great detail. Prices can go as low as 5-10 € per month and billed hourly. Some more screenshots from my machine (no need to be admin to get this info):

![msinfo1](https://github.com/kernelwernel/VMAware/assets/13893067/9b6a4b72-df8d-4440-a4da-c74634021296)
![msinfo2](https://github.com/kernelwernel/VMAware/assets/13893067/aa2aa63b-94fc-4794-b89c-1ea1ff2c1541)
![msinfo3](https://github.com/kernelwernel/VMAware/assets/13893067/9db139ff-be8a-4398-ab83-3d9e032bb27d)
![msinfo4](https://github.com/kernelwernel/VMAware/assets/13893067/0b2e05ef-e84b-45c2-94c8-aebfbb1a3e5e)

**Comment by kernelwernel** [comment]
I've tried to replicate your output and I've found the issue. Should be fixed now.
![image](https://github.com/kernelwernel/VMAware/assets/77142078/5dc8ad06-1a64-4b45-b896-257e5d8d6d27)

Let me know if you encounter any other problems, and thanks for reporting it! :)

**Comment by kernelwernel** [comment]
> There is also lot of QUEMU related hardware devices. You could also rent a virtual computer from various providers such as Hetzner, Contabo, OVH or netcup and examine each virtual machine in great detail. Prices can go as low as 5-10 € per month and billed hourly. Some more screenshots from my machine (no need to be admin to get this info):
> 
> ![msinfo1](https://private-user-images.githubusercontent.com/13893067/307606957-9b6a4b72-df8d-4440-a4da-c74634021296.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5ODMzNzgsIm5iZiI6MTcwODk4MzA3OCwicGF0aCI6Ii8xMzg5MzA2Ny8zMDc2MDY5NTctOWI2YTRiNzItZGY4ZC00NDQwLWE0ZGEtYzc0NjM0MDIxMjk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI2VDIxMzExOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkNDMwMDViOWU4OGIwNDk4NTUzOTI0MWFlYWY2N2M1ZjY0MGFkMzdkYTk1YzA4MmE2ZGZhNThhYzkwNWU4MTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XKZG1r0S9Le-VZxYcOY6wp4OEP3JEe0pXsEI9Ub0bRQ) ![msinfo2](https://private-user-images.githubusercontent.com/13893067/307606960-aa2aa63b-94fc-4794-b89c-1ea1ff2c1541.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5ODMzNzgsIm5iZiI6MTcwODk4MzA3OCwicGF0aCI6Ii8xMzg5MzA2Ny8zMDc2MDY5NjAtYWEyYWE2M2ItOTRmYy00Nzk0LWI4OWMtMWVhMWZmMmMxNTQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI2VDIxMzExOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxZDdkNWI3NWUxY2I3YjIwYzRjMmZkMjIzYjAxZDVkYjQ4YTc3NTdhZGE4MDJjMDViZjcxMjdjZTU3OGZiNjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dlCY6h5yjkRKG93mchtG8UyOm-nyyRKSIC2fCzlVAJg) ![msinfo3](https://private-user-images.githubusercontent.com/13893067/307606965-9db139ff-be8a-4398-ab83-3d9e032bb27d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5ODMzNzgsIm5iZiI6MTcwODk4MzA3OCwicGF0aCI6Ii8xMzg5MzA2Ny8zMDc2MDY5NjUtOWRiMTM5ZmYtYmU4YS00Mzk4LWFiODMtM2Q5ZTAzMmJiMjdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI2VDIxMzExOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5MDk2MmY3ZDYwY2U4YTY0MmQyMzI5NjRhYWFhNWM5NGZkNzhhZDU5Mzc5M2NjNGNmNDE2ZGMxNDg0Yzc2ODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.w1upzua0UAJofY8ZpeDZNsj-z_vGlj0Nw-lIruZUDbY) ![msinfo4](https://private-user-images.githubusercontent.com/13893067/307606973-0b2e05ef-e84b-45c2-94c8-aebfbb1a3e5e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5ODMzNzgsIm5iZiI6MTcwODk4MzA3OCwicGF0aCI6Ii8xMzg5MzA2Ny8zMDc2MDY5NzMtMGIyZTA1ZWYtZTg0Yi00NWMyLTk0YzgtYWViZmJiMWEzZTVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI2VDIxMzExOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViN2RlNTdhMGY4OWE4N2Y3MjhjZjYzZmMyMDk4NGEyNmExZmM1Y2EyMDMyZWM0MmNhNjdiNjYyODJmNDE1YjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.E5C6tDMmPyGbQq2NCItj2kNpUshPxBIqw_JpIQkxetY)

and thanks, i really appreciate the effort. I think I've already added some of those registries but I need to double check. If there are some I haven't added yet then i'll make sure to make some additional techniques. :+1:

**Comment by MarekKnapek** [comment]
Since I already have account with Hetzner and I'm familiar with their user interface, I can create new cheap virtual machine for 1-2 weeks and give you root access to it. I'm thinking something like 2 CPU / 4 GB RAM / 40 GB SSD. What operating system do you prefer? They also offer ARM 64bit computers if you are into this sort of things.

**Comment by kernelwernel** [comment]
> Since I already have account with Hetzner and I'm familiar with their user interface, I can create new cheap virtual machine for 1-2 weeks and give you root access to it. I'm thinking something like 2 CPU / 4 GB RAM / 40 GB SSD. What operating system do you prefer? They also offer ARM 64bit computers if you are into this sort of things.

You sure about this? that would be incredibly helpful! :smile: You can email me the credentials at jeanruyv@gmail.com, or you can add me on discord at `kr.nl` if you have it.
