### ISSUE TITLE
3 tests are broken on windows bare metal

### ISSUE THREAD

**Issue by fameowner99** [NotRequiem/VMAware#59]
![image (1)](https://github.com/kernelwernel/VMAware/assets/34045014/519765ff-28a5-4d98-a9a5-cd192b904246)
![image](https://github.com/kernelwernel/VMAware/assets/34045014/d3c2531d-3127-463b-b1a1-cff3eb7b2f4e)

**Comment by kernelwernel** [comment]
I've disabled the hypervisor bit and hypervisor brand techniques for Windows (by default unless specified with the `VM::WIN_HYPERV_DEFAULT` flag, but I'm not sure about the RDTSC technique. I could either:
1. lower the certainty score
2. increase the RDTSC timestamp threshold bar (from 1500ns to 2000ns)
3. or completely disable it 

I'd like to hear your thoughts.

**Comment by fameowner99** [comment]
I think RDTSC threshold is Ok right now.
I guess test failed because I run debug.
On release all test passed.

**Comment by kernelwernel** [comment]
> I think RDTSC threshold is Ok right now. I guess test failed because I run debug. On release all test passed.

I see, no worries!
