### ISSUE TITLE
typo in constexpr std::array files

### ISSUE THREAD

**Issue by NotRequiem** [NotRequiem/VMAware#6]
at line 2048: "C:\\windows\\System32\\Driversvmhgfs.dll",

should be: "C:\\windows\\System32\\Drivers\\vmhgfs.dll",

Also made other src with the following MSVC compiler errors fixed:
![1](https://github.com/kernelwernel/VMAware/assets/114197630/41e9e048-7137-4e80-ba0b-1a1b0657f685)

src: https://www.mediafire.com/file/1mxgmy64x8bdknl/vmaware.hpp/file

great library by the way

**Comment by kernelwernel** [comment]
Thanks! I really appreciate telling me this issue. 

Is it possible if you can create a pull request so it's easier for me to manage the changes?

**Comment by kernelwernel** [comment]
Fixed #7
