### ISSUE TITLE
Detected some memory leaks

### ISSUE THREAD

**Issue by viceinator** [NotRequiem/VMAware#60]
Calling `VM::brand();` leads to an memory-leak:
https://github.com/kernelwernel/VMAware/blob/5f156e643a56de46cc030e838bd9f57cf4269a8a/src/vmaware.hpp#L2773

---

Same here (`VM::detect();`):
https://github.com/kernelwernel/VMAware/blob/5f156e643a56de46cc030e838bd9f57cf4269a8a/src/vmaware.hpp#L1775

**Comment by kernelwernel** [comment]
fixed [here](https://github.com/kernelwernel/VMAware/commit/ca998574f156746eba2e06842dca4984ff31db35), thanks for reporting this :)
