### ISSUE TITLE
VM::Default inaccessible

### ISSUE THREAD

**Issue by alandtse** [NotRequiem/VMAware#68]
Under VS2022 Version 17.8.3 this example results in an inaccessible member error for `VM::DEFAULT`

```cpp
bool is_vm6 = VM::detect(VM::DEFAULT & ~(VM::RDTSC));
```
![image](https://github.com/kernelwernel/VMAware/assets/7086117/e9b66ab1-cee5-46ab-aa1a-64077480ead3)

I'm on main (so not a release) so let me know if that's the issue. I tried moving 

```cpp
    // global values
    static flagset DEFAULT; // default bitset that will be run if no parameters are specified
```
From `private:` to `public:` but then Default isn't an enum so the & fails. I didn't have much time to play with it so may figure something out.

**Comment by kernelwernel** [comment]
> Under VS2022 Version 17.8.3 this example results in an inaccessible member error for `VM::DEFAULT`
> 
> ```c++
> bool is_vm6 = VM::detect(VM::DEFAULT & ~(VM::RDTSC));
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/7086117/319528629-e9b66ab1-cee5-46ab-aa1a-64077480ead3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyMjg4NDQsIm5iZiI6MTcxMjIyODU0NCwicGF0aCI6Ii83MDg2MTE3LzMxOTUyODYyOS1lOWI2NmFiMS1jZWU1LTQ2YWItYWExYS02NDA3NzQ4MGVhZDMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDRUMTEwMjI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDJhMzRhMGNkMTNjNDJiY2VlNWQ5N2IzMGNjYmFlMjE5NTNlMWI0ZjgzMjdlMzA5NDZiN2MwNTZlZmMxNWQ3MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.WJldlwA1AK5dXtEw35pf_tUTFcFb9alUP1CA-nV7Oew)
> 
> I'm on main (so not a release) so let me know if that's the issue. I tried moving
> 
> ```c++
>     // global values
>     static flagset DEFAULT; // default bitset that will be run if no parameters are specified
> ```
> 
> From `private:` to `public:` but then Default isn't an enum so the & fails. I didn't have much time to play with it so may figure something out.

Fixed! Thanks for reporting the issue. The latest merge has made both VM::DEFAULT and VM::ALL as public.
