### ISSUE TITLE
question: VM directories false detect

### ISSUE THREAD

**Issue by kbetmp001** [NotRequiem/VMAware#77]
im on vmware and I can sure those dirs in source codes does not exist.
{ CWSANDBOX, "c:\\analysis" },
{ VBOX, "%PROGRAMFILES%\\oracle\\virtualbox guest additions\\" },
{ VMWARE, "%PROGRAMFILES%\\VMware\\" }

but util::exists keeps return true when testing the VBOX dir and report me on a virtualbox. 
is this a bug or some deep trick inside?

**Comment by kernelwernel** [comment]
I'll disable that technique then, thanks for sharing this with me.
