### ISSUE TITLE
how do you run the cli tool

### ISSUE THREAD

**Issue by G2G2G2G** [NotRequiem/VMAware#97]
As far as I know a .cpp can't run on windows
Your readme makes it seem like it can, and you just need to DL it and run it?
If so how to do that? I'm unfamiliar with windows.

**Comment by kernelwernel** [comment]
I've added the binary here, thanks for reporting this issue I should've done a while ago tho

https://github.com/kernelwernel/VMAware/releases/download/v1.5/vmaware64.exe

**Comment by kernelwernel** [comment]
@G2G2G2G Hi, sorry to bother you but did you receive this error when running the executable by any chance?

![image](https://github.com/user-attachments/assets/526ddbc5-2325-4a1b-8f4a-e5e23cc5c005)
